global:
  scrape_interval: 15s  # 默认15s采集一次
  external_labels:
    monitor: 'go-micro-prometheus-monitor'
scrape_configs:
  # 监控的服务
  - job_name: 'order'
    scrape_interval: 5s  # 覆盖默认scrape值
    static_configs:
      - targets:
          - docker.for.mac.host.internal:9092